### ISSUE TITLE
Refactor the OSB application to be fully React

### ISSUE THREAD

**Issue by tarelli** [OpenSourceBrain/geppetto-osb#191]
- [x] Setup a call with Dario to help understand the implications of this.
- [ ] Create a diagram to show what components will be used, which ones will be refactored, etc.
- [x] Create sub issues once it's clear what needs to happen (E.g. Port components that are not yet fully React to React (Plot?Popup?Tutorial?), Refactor ComponentsInitialization.js to use React components, etc.)

**Comment by filippomc** [comment]
Added an estimate to bring the application to a stable/working status to start a discussion. Then we probably need to keep separate issues for what we need

**Comment by tarelli** [comment]
@filippomc In the last conversation with @pgleeson we agreed to aim to bring the production deployment to CF/GC using the newest compatible version of Geppetto and to treat for now "fully React" as deferred to optimise the hours in favour of new development.
