### ISSUE TITLE
General update of online documentation/help pages

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#62]
- [x] Videos on http://opensourcebrain.org/docs#Getting_Started are very out of date (sorry @adrianq...)
- [ ] Use examples from core projects which are more up to date
- [x] One page giving background/howto/current options for simulating: https://github.com/OpenSourceBrain/redmine/issues/228
- [x] Gallery view https://github.com/OpenSourceBrain/redmine/issues/303
- [x] 5 minute intro to OSB: https://github.com/OpenSourceBrain/redmine/issues/273
- [x] Page on how to make a new tutorial https://github.com/OpenSourceBrain/geppetto-osb/issues/83

**Comment by pgleeson** [comment]
Will open specific issues...
